# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs


# Added by Antigravity CLI installer
export PATH="/home/wesleyosantos/.local/bin:$PATH"
